from collections.abc import Mapping
from typing import Any, AnyStr, BinaryIO, Literal

from twisted.internet.defer import Deferred
from twisted.internet.interfaces import (
    IAddress,
    IConsumer,
    IOpenSSLClientConnectionCreator,
    IProtocol,
    IPushProducer,
    IStreamClientEndpoint,
)
from twisted.python import urlpath
from twisted.web.client import URI
from twisted.web.http_headers import Headers
from zope.interface import Interface

class IClientRequest(Interface):
    method: bytes
    absoluteURI: bytes | None
    headers: Headers

class IRequest(Interface):
    method: bytes
    uri: bytes
    path: bytes
    args: Mapping[bytes, list[bytes]]
    prepath: list[bytes]
    postpath: list[bytes]
    requestHeaders: Headers
    content: BinaryIO
    responseHeaders: Headers
    def getHeader(key: AnyStr) -> AnyStr | None: ...
    def getCookie(key: bytes) -> bytes | None: ...
    def getAllHeaders() -> dict[bytes, bytes]: ...
    def getRequestHostname() -> bytes: ...
    def getHost() -> IAddress: ...
    def getClientAddress() -> IAddress: ...
    def getClientIP() -> str | None: ...
    def getUser() -> str: ...
    def getPassword() -> str: ...
    def isSecure() -> bool: ...
    def getSession(sessionInterface: Any | None = ...) -> Any: ...
    def URLPath() -> urlpath.URLPath: ...
    def prePathURL() -> bytes: ...
    def rememberRootURL() -> None: ...
    def getRootURL() -> bytes: ...
    def finish() -> None: ...
    def write(data: bytes) -> None: ...
    def addCookie(
        k: AnyStr,
        v: AnyStr,
        expires: AnyStr | None = ...,
        domain: AnyStr | None = ...,
        path: AnyStr | None = ...,
        max_age: AnyStr | None = ...,
        comment: AnyStr | None = ...,
        secure: bool | None = ...,
    ) -> None: ...
    def setResponseCode(code: int, message: bytes | None = ...) -> None: ...
    def setHeader(k: AnyStr, v: AnyStr) -> None: ...
    def redirect(url: AnyStr) -> None: ...
    # returns http.CACHED or False. http.CACHED is a string constant, but we
    # treat it as an opaque object, similar to UNKNOWN_LENGTH.
    def setLastModified(when: float) -> object | Literal[False]: ...
    def setETag(etag: str) -> object | Literal[False]: ...
    def setHost(host: bytes, port: int, ssl: bool = ...) -> None: ...

class IBodyProducer(IPushProducer):
    # Length is either `int` or the opaque object UNKNOWN_LENGTH.
    length: int | object
    def startProducing(consumer: IConsumer) -> Deferred[None]: ...
    def stopProducing() -> None: ...

class IResponse(Interface):
    version: tuple[str, int, int]
    code: int
    phrase: str
    headers: Headers
    length: int | object
    request: IClientRequest
    previousResponse: IResponse | None
    def deliverBody(protocol: IProtocol) -> None: ...
    def setPreviousResponse(response: IResponse) -> None: ...

class IAgent(Interface):
    def request(
        method: bytes,
        uri: bytes,
        headers: Headers | None = ...,
        bodyProducer: IBodyProducer | None = ...,
    ) -> Deferred[IResponse]: ...

class IPolicyForHTTPS(Interface):
    def creatorForNetloc(
        hostname: bytes, port: int
    ) -> IOpenSSLClientConnectionCreator: ...

class IAgentEndpointFactory(Interface):
    def endpointForURI(uri: URI) -> IStreamClientEndpoint: ...

UNKNOWN_LENGTH: object
