name: CI
on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Limit the permissions of the GITHUB_TOKEN.
permissions: {}

jobs:
  check-newsfile:
    name: Check PR has a changelog
    if: ${{ (github.base_ref == 'main' || contains(github.base_ref, 'release-')) && github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      # Required to check out the repo.
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.sha}}
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.11"
      - run: python -m pip install towncrier
      - run: "scripts-dev/check_newsfragment.sh ${{ github.event.number }}"

  checks:
    runs-on: ubuntu-latest
    permissions:
      # Required to check out the repo.
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: matrix-org/setup-python-poetry@5bbf6603c5c930615ec8a29f1b5d7d258d905aa4 # v2
        with:
          python-version: 3.11
          install-project: false

      - name: Import order (isort)
        run: poetry run isort --check --diff .

      - name: Code style (black)
        run: poetry run black --check --diff .

      - name: Semantic checks (ruff)
        # --quiet suppresses the update check.
        run: poetry run ruff --quiet .

      - name: Restore/persist mypy's cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            .mypy_cache
          key: mypy-cache-${{ github.context.sha }}
          restore-keys: mypy-cache-

      - name: Typechecking (mypy)
        run: poetry run mypy

  docker:
    # Sanity check that we can build the x64 image
    runs-on: ubuntu-latest
    permissions:
      # Required to check out the repo.
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4

      - name: Build image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          push: false

  run-tests:
    name: Tests
    if: ${{ !cancelled() && !failure() }} # Allow previous steps to be skipped, but not fail
    needs: [check-newsfile, checks]
    runs-on: ubuntu-latest
    permissions:
      # Required to check out the repo.
      contents: read
    strategy:
      matrix:
        python-version: ['3.9', '3.11']
        test-dir: ['tests', 'matrix_is_tester']

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: matrix-org/setup-python-poetry@5bbf6603c5c930615ec8a29f1b5d7d258d905aa4 # v2
        with:
         python-version: ${{ matrix.python-version }}
      - run: poetry run trial ${{ matrix.test-dir }}

  # a job which runs once all the other jobs are complete, thus allowing PRs to
  # be merged.
  tests-done:
    if: ${{ always() }}
    needs:
      - check-newsfile
      - checks
      - run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: matrix-org/done-action@3409aa904e8a2aaf2220f09bc954d3d0b0a2ee67 # v3
        with:
          needs: ${{ toJSON(needs) }}
          # The newsfile lint may be skipped on non PR builds or on dependabot builds
          skippable:
            check-newsfile

